# parameters

[token]
native = "C2FLR"
underlying = "testXRP"

[bot]
level = "warning"

[flow]
run_time = 120
user_nums = []
actions = []

# structure

[folder]
fasset_bots = "fasset-bots"
secrets = "user_data/secrets"
data_storage = "user_data/data_storage"
log = "user_data/logs"
contract_interfaces = "contracts/interfaces"

[file.contract_addresses]
C2FLR = "contracts/addresses/coston2.json"

# networks

[network.rpc_url]
C2FLR = "https://coston2-api.flare.network/ext/C/rpc"
testXRP = "https://s.altnet.rippletest.net:51234/"

[network.faucet_url]
C2FLR = "https://faucet.flare.network/coston2"
testXRP = "https://faucet.altnet.rippletest.net/accounts"

[network.fdc_url]
C2FLR = "https://testnet-verifier-fdc-test.aflabs.org"

[network.da_url]
C2FLR = "https://ctn2-data-availability.flare.network"

[network.zero_address]
C2FLR = "0x0000000000000000000000000000000000000000"

[network.composer_address]
C2FLR = "0xF32eB6bf2Bc005Fa85eb61dBdc55Fcd60054B281"

[hyperliquid]
eid = 40294

